# This file was generated by GoReleaser. DO NOT EDIT.
cask "uaa-cli" do
  version "0.23.0"

  on_macos do
    on_arm do
      sha256 "e8d92f58d829f232cde4616b85edb481838446d7019b7204925c2c4bf8a2ff60"
      url "https://github.com/cloudfoundry/uaa-cli/releases/download/v#{version}/uaa-darwin-arm64-#{version}"
      binary "uaa-darwin-arm64-0.23.0", target: "uaa"
    end
    on_intel do
      sha256 "ed77f7e70854c5fa4f869c855adb86f5f16a852238de768e0d611633b1835993"
      url "https://github.com/cloudfoundry/uaa-cli/releases/download/v#{version}/uaa-darwin-amd64-#{version}"
      binary "uaa-darwin-amd64-0.23.0", target: "uaa"
    end
  end
  on_linux do
    on_arm do
      sha256 "e3a380ba4d0b76a1bf8ee825f08731a8f77b7fa072f3ba7367483785a0dd4990"
      url "https://github.com/cloudfoundry/uaa-cli/releases/download/v#{version}/uaa-linux-arm64-#{version}"
      binary "uaa-linux-arm64-0.23.0", target: "uaa"
    end
    on_intel do
      sha256 "231ce8268ecdd7629da6d7d11caf9da7e7cb97927214cbbf3a6e437e84cb2470"
      url "https://github.com/cloudfoundry/uaa-cli/releases/download/v#{version}/uaa-linux-amd64-#{version}"
      binary "uaa-linux-amd64-0.23.0", target: "uaa"
    end
  end

  name "uaa-cli"
  desc "CLI for UAA written in Go"
  homepage "https://github.com/cloudfoundry/uaa-cli"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "uaa-cli",
    ]

  postflight do
    if OS.mac?
      Dir.glob("#{staged_path}/uaa*").each do |file|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", file]
      end
    end
  end

  # No zap stanza required
end
