# This file was generated by GoReleaser. DO NOT EDIT.
cask "uaa-cli" do
  version "0.20.2"

  on_macos do
    on_intel do
      sha256 "9b16a17878334782e06efcd99765670c58695a59977077bb797ec4cd0bda8f87"
      url "https://github.com/cloudfoundry/uaa-cli/releases/download/v#{version}/uaa-darwin-amd64-#{version}"
      binary "uaa-darwin-amd64-0.20.2", target: "uaa"
    end
    on_arm do
      sha256 "c01258f53442b7893e7cd691f1e30d98244439850dfcf5e2830f0289af12355a"
      url "https://github.com/cloudfoundry/uaa-cli/releases/download/v#{version}/uaa-darwin-arm64-#{version}"
      binary "uaa-darwin-arm64-0.20.2", target: "uaa"
    end
  end

  on_linux do
    on_intel do
      sha256 "789684f91dbbc19ea3e1d450884bb0733c82d5857323d51d3e51a871b69750c5"
      url "https://github.com/cloudfoundry/uaa-cli/releases/download/v#{version}/uaa-linux-amd64-#{version}"
      binary "uaa-linux-amd64-0.20.2", target: "uaa"
    end
    on_arm do
      sha256 "b5362818e400fc2eec8c11e03ccda587f675dce4b97588faf93f54080c29cf96"
      url "https://github.com/cloudfoundry/uaa-cli/releases/download/v#{version}/uaa-linux-arm64-#{version}"
      binary "uaa-linux-arm64-0.20.2", target: "uaa"
    end
  end

  name "uaa-cli"
  desc "CLI for UAA written in Go"
  homepage "https://github.com/cloudfoundry/uaa-cli"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "uaa-cli",
    ]

  postflight do
    if OS.mac?
      Dir.glob("#{staged_path}/uaa*").each do |file|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", file]
      end
    end
  end

  # No zap stanza required

end
