# This file was generated by GoReleaser. DO NOT EDIT.
cask "uaa-cli" do
  version "0.20.1"

  on_macos do
    on_intel do
      sha256 "5b2a7a757eec270fcc148268612207f816db253b45ffd4e7098f2409313e5971"
      url "https://github.com/cloudfoundry/uaa-cli/releases/download/v#{version}/uaa-darwin-amd64-#{version}"
      binary "uaa-darwin-amd64-0.20.1", target: "uaa"
    end
    on_arm do
      sha256 "442efe9f1f9f8a85d1a78f026331fa1113314458307582a88c3ad208737b82c7"
      url "https://github.com/cloudfoundry/uaa-cli/releases/download/v#{version}/uaa-darwin-arm64-#{version}"
      binary "uaa-darwin-arm64-0.20.1", target: "uaa"
    end
  end

  on_linux do
    on_intel do
      sha256 "15e0c8e2b2b02f72d3d520698a2eedf1cc2b9886a55eb96477a69a159a10b853"
      url "https://github.com/cloudfoundry/uaa-cli/releases/download/v#{version}/uaa-linux-amd64-#{version}"
      binary "uaa-linux-amd64-0.20.1", target: "uaa"
    end
    on_arm do
      sha256 "91579760d1fa8df71f8a1c8c047a5f6035853b0c1737f63a425dda658e0bbc67"
      url "https://github.com/cloudfoundry/uaa-cli/releases/download/v#{version}/uaa-linux-arm64-#{version}"
      binary "uaa-linux-arm64-0.20.1", target: "uaa"
    end
  end

  name "uaa-cli"
  desc "CLI for UAA written in Go"
  homepage "https://github.com/cloudfoundry/uaa-cli"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "uaa-cli",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/uaa"]
    end
  end

  # No zap stanza required

end
